name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Change Directory to LineupList
        run: cd LineupList

      - name: Install dependencies
        run: npm install
        working-directory: ./LineupList

      - name: Build
        env:
          BASE_PATH: '/LineupList'
        run: |
          npm run build
        working-directory: ./LineupList

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'LineupList/build/'  # Path to your build output directory

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
